# Generated by Django 2.2.3 on 2019-08-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0002_auto_20190728_1807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paste',
            old_name='die_time',
            new_name='create_time',
        ),
    ]
