# Generated by Django 2.2.3 on 2019-08-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0003_auto_20190807_1248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paste',
            options={'ordering': ['-create_time']},
        ),
    ]
