# Generated by Django 2.2.3 on 2019-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0004_auto_20190807_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='paste',
            name='die_time',
            field=models.DateTimeField(null=True),
        ),
    ]
