# Generated by Django 2.2.3 on 2019-08-07 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0008_auto_20190807_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='life_time',
            field=models.CharField(choices=[('mins', '10 min'), ('minj', '20 min')], max_length=4),
        ),
    ]
