# Generated by Django 2.2.3 on 2019-08-07 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0009_auto_20190807_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='life_time',
            field=models.DateTimeField(choices=[('mins', '10 min'), ('minj', '20 min')], default=datetime.timedelta(0), max_length=4),
        ),
    ]
