# Generated by Django 2.2.3 on 2019-08-08 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0014_auto_20190808_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='life_time',
            field=models.CharField(choices=[('0:01:00', '1 min'), ('0:10:00', '10 min'), ('1:00:00', '1 hour'), ('1 day, 0:00:00', '1 day'), (datetime.timedelta(7), '1 week'), (datetime.timedelta(30), '1 month'), (datetime.timedelta(365), '1 year'), (datetime.timedelta(0), 'inf')], default=datetime.timedelta(0), max_length=100),
        ),
    ]
