# Generated by Django 2.2.3 on 2019-08-08 10:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0015_auto_20190808_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='life_time',
            field=models.CharField(choices=[('0:01:00', '1 min'), ('0:10:00', '10 min'), ('1:00:00', '1 hour'), ('1 day, 0:00:00', '1 day'), ('7 days, 0:00:00', '1 week'), ('30 days, 0:00:00', '1 month'), ('365 days, 0:00:00', '1 year'), ('0:00:00', 'inf')], default=datetime.timedelta(0), max_length=100),
        ),
    ]
