# Generated by Django 2.2.3 on 2019-08-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0019_auto_20190813_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
    ]
