# Generated by Django 2.2.3 on 2019-08-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0020_auto_20190813_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='title',
            field=models.CharField(db_index=True, default='unknow', max_length=150),
        ),
    ]
